### PR TITLE
Add package name registering for plugins

### PR DESCRIPTION
**Pull request by darrenmce**
Note: i created a repo: https://github.com/darrenmce/oxford-plugin-test and published to npm for testing purposes

### CODE REVIEW

**Comment by snypelife** [comment]
Dude this looks awesome! I'll merge in after #11

**Comment by mpareja** [comment]
It looks like there are a bunch of different ways of registering a plugin but you haven't left the simplest which is just passing in a function. I could imagine that being useful if the plugin needed configuration parameters not unlike express middleware often want.

**Comment by snypelife** [comment]
could just have `registerPlugin` accept a second parameter for config options?

**Comment by mpareja** [comment]
Not sure adding another concept - plugin-options - is really worth it. I was just suggesting that allowing a function to be passed in as a plugin is far more powerful than simply giving a plugin name. (But using plugin names is coolio too!)

**Comment by snypelife** [comment]
i this i see what you mean.  
You can still do this
```js
oxford.registerPlugin({
   hook: 'preget',
   name: 'plugin-name',
   method: function () { 
     // do something
   }
});
```
is that not similar to what you're thinking?

**Comment by mpareja** [comment]
Oh, okay. I didn't grok that!

**Pull request merged**
