### PR TITLE
Feature plugins

### PR DESCRIPTION
**Pull request by snypelife**
Exposes seams that you may register external plugins into the processing/query chain.
[README](https://github.com/snypelife/oxford/blob/feature-plugins/README.md) has more in depth info.

### CODE REVIEW

**Comment by snypelife** [comment]
Hey @darrenmce, would this be useful for you at all?

**Comment by darrenmce** [comment]
very interesting, definitely useful! could refactor some stuff using plugins for sure (markdown for starters)

would you be open to the plugin import scheme similar to eslint or babel6? where you can just refer to the name of a plugin by the string `'markdown'` and it would imply `require('oxford-plugin-markdown')` if it exists

**Comment by snypelife** [comment]
Yeah I was digging into eslint's source for inspiration and to see how they do it.  

I'm definitely interested in investigating that approach.

Brett Rogerson
------------------------
Sent from my iPhone.

On Nov 26, 2015, at 9:36 AM, Darren McElligott <notifications@github.com> wrote:

very interesting, definitely useful! could refactor some stuff using plugins for sure (markdown for starters)

would you be open to the plugin import scheme similar to eslint or babel6? where you can just refer to the name of a plugin by the string 'markdown' and it would imply require('oxford-plugin-markdown') if it exists

**Comment by snypelife** [comment]
For sure man, PR away. I'll merge this guy in and you can branch off of it?

**Comment by snypelife** [comment]
Sorry, just re-read your comment.  You I'm all for you adding to this PR.

**Comment by darrenmce** [comment]
added #12 to add to this PR

**Comment by snypelife** [comment]
shit i think i did this backwards

**Pull request merged**
